# Generated by Django 4.0.6 on 2022-09-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.transaction'),
        ),
    ]
